config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    root "dashboard#index"
    resources :users
    resources :categories
    resources :words
    resources :lessons
    resources :imports, only: :create
  end

  get "users/new"
  get "sessions/new"
  root "static_pages#home"
  get "signup"  => "users#new"
  get    "login"   => "sessions#new"
  post   "login"   => "sessions#create"
  delete "logout"  => "sessions#destroy"
  resources :users
  resources :relationships, only: [:create, :destroy]
  resources :categories, only: [:index]
  resources :words, only: [:index]
  resources :lessons, expect: [:destroy]

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if logged_in?
      @activities_feed = current_user.feed.recent.paginate page: params[:page]
      @results = Result.results_by_user current_user.lessons.pluck(:id)
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/home.html.erb
<div class="row">
  <% if logged_in? %>
    <aside class="col-md-3"> 
      <%= link_to (image_tag (current_user).avatar.url, size: Settings.avatar.image_size), current_user %>
      <h3>
        <%= current_user.name %><br>
        <%= current_user.email %>
      </h3>     
      <section class="stats">
        <%= render "shared/stats" %>
        <b><%= t("static_pages.learned", number_word: @results.count) %></b>
      </section>
    </aside>
    <div class="col-md-6 stylebutton" >
      <%= link_to t("static_pages.word"), words_path,
        class: "action-button shadow animate blue" %>
      <%= link_to t("static_pages.lesson"), categories_path,
        class: "action-button shadow animate red" %>
    </div>
    <%= render "shared/feed" %>
  <% else %>
    <div class="center jumbotron">
      <h1><%= t "static_pages.welcome" %></h1>
      <%= link_to t("static_pages.sign_in"), login_path, class: "btn btn-lg btn-primary" %>
    </div>
  <% end %>
</div>