config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    root "dashboard#index"
    resources :users
    resources :categories
    resources :words
    resources :lessons
    resources :imports, only: :create
  end

  get "users/new"
  get "sessions/new"
  root "static_pages#home"
  get "signup"  => "users#new"
  get    "login"   => "sessions#new"
  post   "login"   => "sessions#create"
  delete "logout"  => "sessions#destroy"
  resources :users
  resources :relationships, only: [:create, :destroy]
  resources :categories, only: [:index]
  resources :words, only: [:index]
  resources :lessons, expect: [:destroy]

end

app/models/word.rb
class Word < ActiveRecord::Base
  belongs_to :category
  has_many :answers, dependent: :destroy

  accepts_nested_attributes_for :answers, allow_destroy: true,
    reject_if: proc {|a| a[:content].blank?}
    
  validates :content, presence: true
  has_many :answers, dependent: :destroy
  has_many :results, dependent: :destroy
    
  scope :of_category, ->category_id{where category_id: category_id if category_id.present?}
  scope :recent, ->{order "created_at DESC"}
  scope :learned, ->current_user_id{where "id IN (SELECT word_id FROM results 
    WHERE lesson_id IN (SELECT id FROM lessons WHERE user_id = ?))", current_user_id}
  scope :not_learned, ->current_user_id{where "id NOT IN (SELECT word_id FROM results 
    WHERE lesson_id IN (SELECT id FROM lessons WHERE user_id = ?))", current_user_id}
  scope :get_all, ->current_user_id{}
end

app/controllers/admin/words_controller.rb
class Admin::WordsController < ApplicationController
  before_action :init_word, only: [:edit, :update, :destroy]

  def index
    respond_to do |format|
      format.html do
        @categories = Category.all
        @words = Word.all
        @word = Word.new
        4.times do 
          @answer = @word.answers.build
        end
      end
      format.csv {send_data export_csv}
    end
  end

  def create
    @word = Word.new word_params
    if @word.save
      respond_to do |format|
        format.html do
          flash[:info] = t "create_word_success_message"
          redirect_to admin_words_path
        end
        format.js
      end
    else
      flash[:now] = t "create_word_failed_message"
      redirect_to admin_words_path
    end
  end

  def edit
  end

  def update
    if @word.update_attributes word_params
      flash[:sucess] = t "update_sucessfull_message"
      redirect_to admin_words_path
    else
      render :edit
      flash.now[:danger] = t "update_failed_message"
    end
  end

  def destroy
    if @word.destroy
      respond_to do |format|
        format.html do
          flash[:info] = t "destroy_word_success_message"
          redirect_to admin_words_path
        end
        format.js
      end
    else
      flash[:now] = t "destroy_word_failed_message"
    end
  end
  
  private
  def init_word
    @word = Word.find params[:id]
  end

  def word_params
    params.require(:word).permit :content, :category_id, answers_attributes: [:id, :content, :status]
  end

  def export_csv
    headers = Settings.csv_header
    CSV.generate(headers: true) do |csv|
      csv << headers
      Category.all.each do |category|
        category.words.each do |word|
          word.answers.each do |answer|
            csv << [category.name, word.content, answer.content, answer.status]
          end
        end
      end
    end
  end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  before_action :logged_in_user

  def index
    @categories= Category.all
    if params[:filter_state]
      @words = Word.of_category(params[:category_id]).send(params[:filter_state], current_user.id)
        .paginate page: params[:page]
    else
      @words = Word.of_category(params[:category_id]).paginate page: params[:page]
    end
  end
end

app/views/admin/words/_word.html.erb
<% word.answers.each do |answer| %>
  <tr id="word-<%= word.id %>">
    <td><%= word.category.name %></td>
    <td><b><%= word.content %></b></td>
    <td><%= answer.content %></td>
    <td><b><%= answer.status %></b></td>
    <td>
      <%= link_to "" , admin_word_path(word), method: :delete,
        data: {confirm: t("confirm_action", action: t("delete"))},
        class: "glyphicon glyphicon-remove" %>
      <%= link_to "", edit_admin_word_path(word),
        class: "glyphicon glyphicon-edit" %>
    </td>
  </tr>
<% end %>

app/views/admin/words/edit.html.erb
 <div class="col-md-4">
    <div>
      <%= form_for [:admin, @word], class: "form" do |f| %>
        <%= render "shared/error_messages", object: f.object %>
        <div class="form-group">
          <%= f.label t "word" %>
          <%= f.text_field :content, class: "form-control" %>
        </div>
        <div class="form-group" id="means">
          <div id="answer_list">
            <%= f.fields_for :answers, wrapper: true do |answer_form| %>
              <%= render "shared/error_messages", object: answer_form.object %>
              <div class="row answer-form">
                <div class="col-md-5">
                  <%= answer_form.label t "answer" %>
                  <%= answer_form.text_field :content, required: true, class: "form-control" %>
                </div>
                <div class="col-md-3">
                  <%= answer_form.label t "correct" %>
                  <%= answer_form.check_box :status, class: "checkbox" %>
                </div>
              </div>
            <% end %>
          </div>
        </div>
        <br>
        <%= f.submit t("done"), class: "btn btn-primary pull-right" %>
      <% end %>
    </div>
  </div>
</div>

<%= javascript_include_tag "select_only_one_checkbox", "data-turbolinks-track" => true %>

app/views/admin/words/index.html.erb
<br>
<div class="row">
  <div class="col-md-8">
    <div class="row">
      <h3 class="text-info">
        <%= t "import_csv_file" %>
      </h3>
      <%= form_tag admin_imports_path, method: :post, multipart: true do %>
        <div class="col-md-11">
          <%= file_field_tag :file, class: "filestyle", required: true %>
        </div>
        <div class="col-md-1">
          <%= submit_tag t("submit_csv_file"), class: "btn btn-primary pull-right" %>
        </div>
      <% end %>
    </div>
    <hr>
    <table id="word_list_table" class="table table-hover table-bordered text-center">
      <tbody>
        <tr>
          <th class="text-center"><%= t "category" %></th>
          <th class="text-center"><%= t "word" %></th>
          <th class="text-center"><%= t "answer" %></th>
          <th class="text-center"><%= t "status" %></th>
          <th class="text-center"><%= t "tool" %></th>
        </tr>
        <% @words.each do |word| %>
          <%= render "admin/words/word", word: word %>
        <% end %>
      </tbody>  
    </table>
    <a href="<%= admin_words_path(format: "csv") %>" class="btn btn-primary">
      <span class="glyphicon glyphicon-download-alt"></span><%= t "download" %>
    </a>
  </div>
  <div class="col-md-4">
    <div>
      <%= form_for [:admin, @word], class: "form" do |f| %>
        <%= render "shared/error_messages", object: f.object %>
        <div class="form-group">
          <%= f.label t "word" %>
          <%= f.text_field :content, class: "form-control", placeholder: t("enter_new_word") %>
        </div>
        <div class="form-group">
          <%= f.label :category_id %>
          <%= f.select :category_id, options_for_select(@categories.map{|c| [c.name, c.id ]}, 
            selected_key = f.object.category_id), {}, class: "form-control" %>
        </div>
        <div class="form-group" id="means">
          <div id="answer_list">
            <%= f.fields_for :answers, wrapper: true do |answer_form| %>
              <%= render "shared/error_messages", object: answer_form.object %>
              <div class="row answer-form">
                <div class="col-md-5">
                  <%= answer_form.label t "answer" %>
                  <%= answer_form.text_field :content, required: true, class: "form-control" %>
                </div>
                <div class="col-md-3">
                  <%= answer_form.label t "correct" %>
                  <%= answer_form.check_box :status, class: "checkbox" %>
                </div>
              </div>
            <% end %>
          </div>
        </div>
        <br>
        <%= f.submit t("done"), class: "btn btn-primary pull-right" %>
      <% end %>
    </div>
  </div>
</div>

<%= javascript_include_tag "select_only_one_checkbox", "data-turbolinks-track": true %>