config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    root "dashboard#index"
    resources :users
    resources :categories
    resources :words
    resources :lessons
    resources :imports, only: :create
  end

  get "users/new"
  get "sessions/new"
  root "static_pages#home"
  get "signup"  => "users#new"
  get    "login"   => "sessions#new"
  post   "login"   => "sessions#create"
  delete "logout"  => "sessions#destroy"
  resources :users
  resources :relationships, only: [:create, :destroy]
  resources :categories, only: [:index]
  resources :words, only: [:index]
  resources :lessons, expect: [:destroy]

end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController
  def index
    @users_length = User.count
    @categories_length = Category.count
    @words_length = Word.count
    @lessons_length = Lesson.count
  end
end

app/views/admin/dashboard/index.html.erb
<%= provide :title, t("dashboard").titleize %>
<h1><%= t "admin_dashboard.header" %></h1>
<div class="row">
  <%= link_to t("admin_dashboard.users") + @users_length.to_s, admin_users_path,
    class: "col-md-3 admin_interface_style" %>
  <%= link_to t("admin_dashboard.categories") + @categories_length.to_s, admin_categories_path,
    class: "col-md-3 admin_interface_style" %>
  <%= link_to t("admin_dashboard.words") + @words_length.to_s, admin_words_path, 
    class: "col-md-3 admin_interface_style" %>
  <%= link_to t("admin_dashboard.lessons") + @lessons_length.to_s, "#", 
    class: "col-md-3 admin_interface_style" %>
</div>