config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    root "dashboard#index"
    resources :users
    resources :categories
    resources :words
    resources :lessons
    resources :imports, only: :create
  end

  get "users/new"
  get "sessions/new"
  root "static_pages#home"
  get "signup"  => "users#new"
  get    "login"   => "sessions#new"
  post   "login"   => "sessions#create"
  delete "logout"  => "sessions#destroy"
  resources :users
  resources :relationships, only: [:create, :destroy]
  resources :categories, only: [:index]
  resources :words, only: [:index]
  resources :lessons, expect: [:destroy]

end

app/models/activity.rb
class Activity < ActiveRecord::Base
  belongs_to :user
  validates :user_id, presence: true 
  validates :content, presence: true
  validates :content_id, presence: true
  scope :recent, ->{order "created_at DESC"}
  
  def type
    content == Settings.learned ? Lesson.find(content_id) : User.find(user_id)  
  end
end

app/views/activities/_activity.html.erb
<li id="activity-<%= activity.id %>">
  <% type = activity.type %>
  <%= link_to (image_tag @user.avatar.url, size: Settings.avatar.image_size_edit), activity.user %>
  <span class="user"><%= link_to activity.user.name, activity.user %></span>
  <% if activity.content == Settings.learned %>
    <%= t("activity.from", number_word: type.results.count) %>
    <b><%= link_to type.category.name, lesson_path(type) %></b>
  <% else %>
    <b><%= link_to type.name, type %></b>
  <% end %>
  <span class="timestamp">
    <%= t "activity.posted" %><%= time_ago_in_words(activity.created_at) %> ago.
  </span>
</li>